# Generated by Django 3.2 on 2021-05-24 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='email')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('parents_phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('branch', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('roll_no', models.CharField(max_length=30, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
