# Generated by Django 3.2 on 2021-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_teacher',
            field=models.CharField(default='no', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_teacher',
            field=models.CharField(default='no', max_length=30),
        ),
    ]
