# Generated by Django 3.2 on 2021-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20210525_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_teacher',
            field=models.CharField(default='yes', max_length=30),
        ),
    ]
