# Generated by Django 3.2 on 2021-05-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_teacher_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='empty', max_length=30),
        ),
    ]
